[package]
name = "git-gone"
version = "0.3.6"
description = "Manage \"gone\" Git branches"
homepage = "https://github.com/lunaryorn/git-gone"
repository = "https://github.com/lunaryorn/git-gone"
readme = "git-gone.1.adoc"
license = "Apache-2.0"
keywords = ["git", "branch", "remote"]
categories = ["development-tools", "command-line-utilities"]
authors = ["Sebastian Wiesner <sebastian@swsnr.de>"]
edition = "2018"
include = ["git-gone.1", "git-gone.1.adoc"]

[dependencies]
clap = "^2"

[[bin]]
name = "git-gone"
path = "src/main.rs"

[dependencies.git2]
version = "^0.13"
# Disable all features of git2; we only use a small subset of the library and do not need any of these.
# Specifically this also disables SSL and SSH support and thus removes library dependencies, which permits
# a static musl build.
default-features = false
